apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cockroach-local-auto
  annotations:
    defaultVolumeType: local
provisioner: cockroach.local/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cockroachdb-local
  labels:
    storage-owner: cockroachdb
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cockroach-local-auto
  claimRef:
    namespace: cockroach
    name: local-data-cockroachdb-0
  local:
    path: /var/lib/cockroachdb/cockroach
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [aks-main-11118102-vmss000001]
